title: Md Mujahedul Azad (Turin)
description: Competitive Programmer
baseurl: "/resume/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "matkhan01@gmail.com"
linkedin: "http://linkedin.com/in/mdturin"
github: "https://github.com/mdturin"
website: "*"
medium: "*"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
